name = "graphql_mesh"
main = "src/index.ts"
compatibility_date = "2022-06-27"
account_id = "47efd9199a2f2a26049d85b9d3dfe31a"
usage_model = "bundled"
node_compat=true
kv_namespaces = [
  { binding = "MESH", id = "6efcacf054f9427e8b5f70b28da08e07", preview_id = "0418af2eda0646928a23850d278837e5" }
]

[vars]
DEBUG = "1"
GRAPHQL_API = "https://api.spacex.land/graphql/"

