name: Canary Release

on:
  pull_request:
    branches:
      - master
    paths:
      - '.changeset/**/*.md'
  workflow_dispatch:
    inputs:
      onDemand:
        description: 'Are you sure?'
        required: true
        default: 'yes'
      npmTag:
        description: 'NPM Tag'
        required: true
        default: 'alpha'
jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.inputs.onDemand == 'yes'
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: node-modules-cache-canary
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-18-node-modules-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-18-node-modules-

      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines --frozen-lockfile --immutable
        if: steps.node-modules-cache-canary.outputs.cache-hit != 'true'

      - name: Release Canary
        id: canary
        uses: 'the-guild-org/changesets-snapshot-action@v0.0.1'
        with:
          tag: ${{github.event.inputs.npmTag || 'alpha'}}
          prepareScript: 'yarn build'
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
